//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minint.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionesCorreo
    {
        public int IDNotificacionesCorreo { get; set; }
        public string HTMLTemplate { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string Destinatarios { get; set; }
        public bool Enviado { get; set; }
        public string Cco { get; set; }
    }
}
